### ISSUE TITLE
Updated

### ISSUE THREAD

**Issue by jgrau90** [jimmy-jia/LoL-Match-Data-WDC#1]
Hi, i would like to use that connector but it takes so long and i don't know if it works or not. can u check it if it needs an update, it would be great to use it. Im using tableau 10.5

nice work!

**Comment by jimmy-jia** [comment]
Hi, I believe the problem is likely that the League of Legends API has significantly changed since this WDC was created. Unfortunately I don't have the time to look into this at the moment, but feel free to fork or submit a pull request if you want to try taking a look at the API (https://developer.riotgames.com/).

Thanks!
